name: Deploy Angular in FireBase

on:
  push:
    branches:
      - dev

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - run: npm install
      - run: npx ng build --configuration=production

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v12.4.0

        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//0gjaxi9uPyoRJCgYIARAAGBASNwF-L9Ir7lrVFdrw9OKA-IzTk80tTyzctafrHCqMeSHiNwIkPtUc8pTs1rKv2SK1XvcegJzmzu4
