name: Build & Deploy to Firebase

on:
  push:
    branches:
      - dev

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install project dependencies
        run: npm install

      - name: Build Angular application

        run: npx ng build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v12.4.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//0gjaxi9uPyoRJCgYIARAAGBASNwF-L9Ir7lrVFdrw9OKA-IzTk80tTyzctafrHCqMeSHiNwIkPtUc8pTs1rKv2SK1XvcegJzmzu4
