name: Build & Deploy to Firebase

on:
  push:
    branches:
      - dev

jobs:
  Build-Deploy-to-Firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install angular dependencies
        run: npm install -g @angular/cli

      - name: Install project dependencies
        run: npm install --force

      - name: install tslib dependencies
        run: npx install tslib@latest

      - name: Build Angular application
        run: npx ng build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v12.4.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
